import { PrismaClient, ModuleCategory } from '@prisma/client';

const prisma = new PrismaClient();

interface ModuleTypeData {
  name: string;
  description: string;
  category: ModuleCategory;
  maxLevel: number;
  baseHullPoints: number;
  baseDamage: number;
  baseShieldStrength: number;
  baseSensorRange: number;
  baseCargoCapacity: number;
  baseCrewCapacity: number;
  baseSpeed: number;
  hyperdriveRating: number | null;
  tibannaConsumption: number;
  baseCostCredits: number;
  baseCostDurastahl: number;
  baseCostKyberKristalle: number;
  baseCostTibannaGas: number;
  baseCostBeskar: number;
  baseCostKristallinesSilizium: number;
  baseCostEnergiemodule: number;
  baseBuildTime: number;
  requiredResearchId: number | null;
  requiredResearchLevel: number;
}

const moduleTypes: ModuleTypeData[] = [
  // =====================================================
  // HYPERDRIVE MODULE - Hyperantriebe
  // =====================================================
  {
    name: 'Klasse-4 Hyperantrieb',
    description: 'Einfacher Hyperantrieb fuer kurze Spruenge. Langsam aber guenstig.',
    category: 'HYPERDRIVE',
    maxLevel: 5,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: 4.0,
    tibannaConsumption: 0,
    baseCostCredits: 500,
    baseCostDurastahl: 100,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 50,
    baseCostEnergiemodule: 20,
    baseBuildTime: 5,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Klasse-3 Hyperantrieb',
    description: 'Standard-Hyperantrieb fuer die meisten zivilen Schiffe.',
    category: 'HYPERDRIVE',
    maxLevel: 7,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: 3.0,
    tibannaConsumption: 0,
    baseCostCredits: 1000,
    baseCostDurastahl: 200,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 100,
    baseCostEnergiemodule: 40,
    baseBuildTime: 8,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Klasse-2 Hyperantrieb',
    description: 'Schneller Hyperantrieb, Standard fuer militaerische Schiffe.',
    category: 'HYPERDRIVE',
    maxLevel: 8,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: 2.0,
    tibannaConsumption: 0,
    baseCostCredits: 2500,
    baseCostDurastahl: 400,
    baseCostKyberKristalle: 10,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 200,
    baseCostEnergiemodule: 80,
    baseBuildTime: 12,
    requiredResearchId: null, // TODO: Link to research
    requiredResearchLevel: 2,
  },
  {
    name: 'Klasse-1 Hyperantrieb',
    description: 'Hochleistungs-Hyperantrieb. Sehr schnell und effizient.',
    category: 'HYPERDRIVE',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: 1.0,
    tibannaConsumption: 0,
    baseCostCredits: 5000,
    baseCostDurastahl: 800,
    baseCostKyberKristalle: 30,
    baseCostTibannaGas: 0,
    baseCostBeskar: 50,
    baseCostKristallinesSilizium: 400,
    baseCostEnergiemodule: 150,
    baseBuildTime: 20,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },
  {
    name: 'Klasse-0.5 Hyperantrieb',
    description: 'Legendaerer Antrieb. Nur die schnellsten Schiffe der Galaxis nutzen diesen Typ.',
    category: 'HYPERDRIVE',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 3,
    baseSpeed: 0,
    hyperdriveRating: 0.5,
    tibannaConsumption: 0,
    baseCostCredits: 15000,
    baseCostDurastahl: 1500,
    baseCostKyberKristalle: 100,
    baseCostTibannaGas: 50,
    baseCostBeskar: 200,
    baseCostKristallinesSilizium: 800,
    baseCostEnergiemodule: 300,
    baseBuildTime: 45,
    requiredResearchId: null,
    requiredResearchLevel: 5,
  },

  // =====================================================
  // SUBLIGHT ENGINE MODULE - Sublicht-Antriebe
  // =====================================================
  {
    name: 'Sublicht-Ionenantrieb',
    description: 'Standard-Ionenantrieb fuer Sublicht-Geschwindigkeit.',
    category: 'SUBLIGHT_ENGINE',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 5,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 300,
    baseCostDurastahl: 80,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 30,
    baseCostEnergiemodule: 15,
    baseBuildTime: 3,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Hochleistungs-Ionenantrieb',
    description: 'Verbesserter Ionenantrieb mit hoeherer Schubkraft.',
    category: 'SUBLIGHT_ENGINE',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 8,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 800,
    baseCostDurastahl: 150,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 10,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 60,
    baseCostEnergiemodule: 30,
    baseBuildTime: 5,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },
  {
    name: 'SFS P-s4 Zwillingsionenantrieb',
    description: 'Der beruechtigte TIE-Fighter-Antrieb. Extrem schnell aber laut.',
    category: 'SUBLIGHT_ENGINE',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 0,
    baseSpeed: 12,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 2000,
    baseCostDurastahl: 300,
    baseCostKyberKristalle: 5,
    baseCostTibannaGas: 30,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 120,
    baseCostEnergiemodule: 60,
    baseBuildTime: 10,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },

  // =====================================================
  // WEAPONS MODULE - Waffen
  // =====================================================
  {
    name: 'Leichte Laserkanone',
    description: 'Standard-Laserkanone fuer kleine Schiffe.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 8,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 0,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 1,
    baseCostCredits: 400,
    baseCostDurastahl: 100,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 20,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 20,
    baseCostEnergiemodule: 10,
    baseBuildTime: 3,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Zwillings-Laserkanone',
    description: 'Doppelte Feuerrate durch gekoppelte Laserkanonen.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 15,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 2,
    baseCostCredits: 900,
    baseCostDurastahl: 200,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 40,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 40,
    baseCostEnergiemodule: 25,
    baseBuildTime: 5,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Turbolaser Mk.I',
    description: 'Schwere Bordwaffe. Standard-Bewaffnung fuer Korvetten und groessere Schiffe.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 25,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 5,
    baseCostCredits: 2000,
    baseCostDurastahl: 400,
    baseCostKyberKristalle: 5,
    baseCostTibannaGas: 100,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 80,
    baseCostEnergiemodule: 50,
    baseBuildTime: 10,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },
  {
    name: 'Turbolaser Mk.II',
    description: 'Verbesserte Version mit hoeherer Feuerrate und Durchschlagskraft.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 40,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 3,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 8,
    baseCostCredits: 4000,
    baseCostDurastahl: 700,
    baseCostKyberKristalle: 15,
    baseCostTibannaGas: 200,
    baseCostBeskar: 20,
    baseCostKristallinesSilizium: 150,
    baseCostEnergiemodule: 100,
    baseBuildTime: 18,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },
  {
    name: 'Schwerer Turbolaser',
    description: 'Massive Waffe fuer Grosskapitaelschiffe. Kann Schilde durchschlagen.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 70,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 5,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 15,
    baseCostCredits: 10000,
    baseCostDurastahl: 1500,
    baseCostKyberKristalle: 40,
    baseCostTibannaGas: 500,
    baseCostBeskar: 80,
    baseCostKristallinesSilizium: 300,
    baseCostEnergiemodule: 200,
    baseBuildTime: 35,
    requiredResearchId: null,
    requiredResearchLevel: 4,
  },
  {
    name: 'Ionenkanone',
    description: 'Spezialisiert auf das Deaktivieren feindlicher Systeme und Schilde.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 12,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 4,
    baseCostCredits: 1800,
    baseCostDurastahl: 300,
    baseCostKyberKristalle: 10,
    baseCostTibannaGas: 80,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 150,
    baseCostEnergiemodule: 80,
    baseBuildTime: 12,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },
  {
    name: 'Protonenraketen-Werfer',
    description: 'Raketenwerfer fuer hohen Burst-Schaden gegen grosse Ziele.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 50,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0, // Verbraucht Raketen, nicht Tibanna
    baseCostCredits: 3500,
    baseCostDurastahl: 500,
    baseCostKyberKristalle: 20,
    baseCostTibannaGas: 0,
    baseCostBeskar: 30,
    baseCostKristallinesSilizium: 100,
    baseCostEnergiemodule: 60,
    baseBuildTime: 15,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },
  {
    name: 'Konvergenz-Torpedowerfer',
    description: 'Schwere Anti-Kapital-Waffe. Langsam aber verheerend.',
    category: 'WEAPONS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 100,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 3,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 8000,
    baseCostDurastahl: 1000,
    baseCostKyberKristalle: 50,
    baseCostTibannaGas: 0,
    baseCostBeskar: 100,
    baseCostKristallinesSilizium: 200,
    baseCostEnergiemodule: 120,
    baseBuildTime: 30,
    requiredResearchId: null,
    requiredResearchLevel: 4,
  },

  // =====================================================
  // SHIELDS MODULE - Schilde
  // =====================================================
  {
    name: 'Deflektorschild-Generator Mk.I',
    description: 'Basis-Schildgenerator fuer leichten Schutz.',
    category: 'SHIELDS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 20,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 600,
    baseCostDurastahl: 100,
    baseCostKyberKristalle: 5,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 80,
    baseCostEnergiemodule: 40,
    baseBuildTime: 5,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Deflektorschild-Generator Mk.II',
    description: 'Verbesserter Schildgenerator mit schnellerer Regeneration.',
    category: 'SHIELDS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 40,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 1500,
    baseCostDurastahl: 250,
    baseCostKyberKristalle: 15,
    baseCostTibannaGas: 0,
    baseCostBeskar: 10,
    baseCostKristallinesSilizium: 180,
    baseCostEnergiemodule: 90,
    baseBuildTime: 10,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },
  {
    name: 'Deflektorschild-Generator Mk.III',
    description: 'Militaerischer Schildgenerator mit hoher Belastbarkeit.',
    category: 'SHIELDS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 70,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 3,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 3500,
    baseCostDurastahl: 500,
    baseCostKyberKristalle: 35,
    baseCostTibannaGas: 0,
    baseCostBeskar: 40,
    baseCostKristallinesSilizium: 350,
    baseCostEnergiemodule: 180,
    baseBuildTime: 20,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },
  {
    name: 'Schwerer Deflektorschild-Generator',
    description: 'Kapitaelschiff-Schild. Kann enormen Schaden absorbieren.',
    category: 'SHIELDS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 120,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 5,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 8000,
    baseCostDurastahl: 1000,
    baseCostKyberKristalle: 80,
    baseCostTibannaGas: 0,
    baseCostBeskar: 120,
    baseCostKristallinesSilizium: 600,
    baseCostEnergiemodule: 350,
    baseBuildTime: 40,
    requiredResearchId: null,
    requiredResearchLevel: 4,
  },
  {
    name: 'Partikelschild',
    description: 'Spezialisiert auf physischen Schutz gegen Projektile und Truemmer.',
    category: 'SHIELDS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 30,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 800,
    baseCostDurastahl: 200,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 30,
    baseCostKristallinesSilizium: 100,
    baseCostEnergiemodule: 50,
    baseBuildTime: 8,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },

  // =====================================================
  // SENSORS MODULE - Sensoren
  // =====================================================
  {
    name: 'Basis-Sensorarray',
    description: 'Einfaches Sensorpaket fuer Navigation und Zielerfassung.',
    category: 'SENSORS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 3,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 300,
    baseCostDurastahl: 50,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 100,
    baseCostEnergiemodule: 30,
    baseBuildTime: 3,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Erweitertes Sensorarray',
    description: 'Verbessertes Sensorpaket mit groesserer Reichweite.',
    category: 'SENSORS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 5,
    baseCargoCapacity: 0,
    baseCrewCapacity: 1,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 800,
    baseCostDurastahl: 100,
    baseCostKyberKristalle: 5,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 200,
    baseCostEnergiemodule: 60,
    baseBuildTime: 6,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },
  {
    name: 'Militaerisches Langstrecken-Sensorarray',
    description: 'Hochpraezise Sensoren fuer Aufklaerung und Fruehwarnung.',
    category: 'SENSORS',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 8,
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 2000,
    baseCostDurastahl: 200,
    baseCostKyberKristalle: 15,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 400,
    baseCostEnergiemodule: 120,
    baseBuildTime: 12,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },

  // =====================================================
  // CARGO MODULE - Frachtraum
  // =====================================================
  {
    name: 'Standard-Frachtraum',
    description: 'Basis-Laderaum fuer Gueter und Ausruestung.',
    category: 'CARGO',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 50,
    baseCrewCapacity: 0,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 200,
    baseCostDurastahl: 80,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 10,
    baseCostEnergiemodule: 5,
    baseBuildTime: 2,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Erweiterter Frachtraum',
    description: 'Groesserer Laderaum mit effizienter Raumnutzung.',
    category: 'CARGO',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 150,
    baseCrewCapacity: 0,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 600,
    baseCostDurastahl: 200,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 30,
    baseCostEnergiemodule: 15,
    baseBuildTime: 5,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Schwerer Frachtraum',
    description: 'Massiver Laderaum fuer Transporter und Frachtschiffe.',
    category: 'CARGO',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 400,
    baseCrewCapacity: 0,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 1500,
    baseCostDurastahl: 500,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 80,
    baseCostEnergiemodule: 40,
    baseBuildTime: 12,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },

  // =====================================================
  // LIFE SUPPORT MODULE - Lebenserhaltung
  // =====================================================
  {
    name: 'Basis-Lebenserhaltung',
    description: 'Standard-System fuer kleine Crews.',
    category: 'LIFE_SUPPORT',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 5,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 400,
    baseCostDurastahl: 60,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 40,
    baseCostEnergiemodule: 30,
    baseBuildTime: 4,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Erweitertes Lebenserhaltungssystem',
    description: 'Fuer mittelgrosse Schiffe mit mehr Crew.',
    category: 'LIFE_SUPPORT',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 20,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 1200,
    baseCostDurastahl: 150,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 100,
    baseCostEnergiemodule: 80,
    baseBuildTime: 8,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },
  {
    name: 'Grossschiff-Lebenserhaltung',
    description: 'Industrielle Lebenserhaltung fuer Kapitaelschiffe.',
    category: 'LIFE_SUPPORT',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 100,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 4000,
    baseCostDurastahl: 400,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 300,
    baseCostEnergiemodule: 200,
    baseBuildTime: 20,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },

  // =====================================================
  // HULL MODULE - Huellenpanzerung
  // =====================================================
  {
    name: 'Leichte Durastahl-Panzerung',
    description: 'Basis-Panzerung aus Durastahl.',
    category: 'HULL',
    maxLevel: 10,
    baseHullPoints: 30,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 0,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 300,
    baseCostDurastahl: 150,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 0,
    baseCostEnergiemodule: 0,
    baseBuildTime: 3,
    requiredResearchId: null,
    requiredResearchLevel: 1,
  },
  {
    name: 'Schwere Durastahl-Panzerung',
    description: 'Verstaerkte Panzerung fuer besseren Schutz.',
    category: 'HULL',
    maxLevel: 10,
    baseHullPoints: 60,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 0,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 800,
    baseCostDurastahl: 400,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 0,
    baseCostEnergiemodule: 0,
    baseBuildTime: 7,
    requiredResearchId: null,
    requiredResearchLevel: 2,
  },
  {
    name: 'Beskar-verstaerkte Panzerung',
    description: 'Mit Beskar legierte Panzerung. Nahezu unzerstoerbar.',
    category: 'HULL',
    maxLevel: 10,
    baseHullPoints: 120,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 0,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 0,
    baseCostCredits: 3000,
    baseCostDurastahl: 600,
    baseCostKyberKristalle: 0,
    baseCostTibannaGas: 0,
    baseCostBeskar: 200,
    baseCostKristallinesSilizium: 0,
    baseCostEnergiemodule: 0,
    baseBuildTime: 20,
    requiredResearchId: null,
    requiredResearchLevel: 4,
  },

  // =====================================================
  // TRACTOR BEAM MODULE - Traktorstrahl
  // =====================================================
  {
    name: 'Leichter Traktorstrahl-Projektor',
    description: 'Fuer das Einfangen kleiner Objekte und Schiffe.',
    category: 'TRACTOR_BEAM',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 3,
    baseCostCredits: 1500,
    baseCostDurastahl: 300,
    baseCostKyberKristalle: 20,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 200,
    baseCostEnergiemodule: 100,
    baseBuildTime: 15,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },
  {
    name: 'Schwerer Traktorstrahl-Projektor',
    description: 'Kann grosse Schiffe immobilisieren. Standard auf Sternzerstoerern.',
    category: 'TRACTOR_BEAM',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 5,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 8,
    baseCostCredits: 5000,
    baseCostDurastahl: 700,
    baseCostKyberKristalle: 60,
    baseCostTibannaGas: 0,
    baseCostBeskar: 50,
    baseCostKristallinesSilizium: 500,
    baseCostEnergiemodule: 250,
    baseBuildTime: 35,
    requiredResearchId: null,
    requiredResearchLevel: 4,
  },

  // =====================================================
  // SPECIAL MODULE - Spezialmodule
  // =====================================================
  {
    name: 'Stoerfeld-Generator',
    description: 'Stoert feindliche Sensoren und Kommunikation.',
    category: 'SPECIAL',
    maxLevel: 10,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: -2, // Reduziert feindliche Sensoren
    baseCargoCapacity: 0,
    baseCrewCapacity: 2,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 2,
    baseCostCredits: 2000,
    baseCostDurastahl: 200,
    baseCostKyberKristalle: 30,
    baseCostTibannaGas: 0,
    baseCostBeskar: 0,
    baseCostKristallinesSilizium: 300,
    baseCostEnergiemodule: 150,
    baseBuildTime: 18,
    requiredResearchId: null,
    requiredResearchLevel: 3,
  },
  {
    name: 'Tarnvorrichtung',
    description: 'Experimentelle Technologie zum Verstecken vor Sensoren.',
    category: 'SPECIAL',
    maxLevel: 5,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 3,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 10,
    baseCostCredits: 20000,
    baseCostDurastahl: 500,
    baseCostKyberKristalle: 200,
    baseCostTibannaGas: 100,
    baseCostBeskar: 150,
    baseCostKristallinesSilizium: 800,
    baseCostEnergiemodule: 500,
    baseBuildTime: 60,
    requiredResearchId: null,
    requiredResearchLevel: 5,
  },
  {
    name: 'Gravitationsbrunnen-Generator',
    description: 'Verhindert feindliche Hypersprung-Flucht. Sehr teuer.',
    category: 'SPECIAL',
    maxLevel: 5,
    baseHullPoints: 0,
    baseDamage: 0,
    baseShieldStrength: 0,
    baseSensorRange: 0,
    baseCargoCapacity: 0,
    baseCrewCapacity: 10,
    baseSpeed: 0,
    hyperdriveRating: null,
    tibannaConsumption: 20,
    baseCostCredits: 50000,
    baseCostDurastahl: 2000,
    baseCostKyberKristalle: 500,
    baseCostTibannaGas: 200,
    baseCostBeskar: 300,
    baseCostKristallinesSilizium: 1500,
    baseCostEnergiemodule: 1000,
    baseBuildTime: 120,
    requiredResearchId: null,
    requiredResearchLevel: 5,
  },
];

async function seedModules() {
  console.log('🚀 Starte ModuleType Seeding...\n');

  for (const moduleData of moduleTypes) {
    const existing = await prisma.moduleType.findUnique({
      where: { name: moduleData.name },
    });

    if (existing) {
      console.log(`  ⏭️  ${moduleData.name} existiert bereits, ueberspringe...`);
      continue;
    }

    await prisma.moduleType.create({
      data: moduleData,
    });

    console.log(`  ✅ ${moduleData.name} erstellt`);
  }

  console.log('\n✨ ModuleType Seeding abgeschlossen!');
  console.log(`   ${moduleTypes.length} Module definiert`);

  // Statistik ausgeben
  const counts = await prisma.moduleType.groupBy({
    by: ['category'],
    _count: true,
  });

  console.log('\n📊 Module nach Kategorie:');
  for (const c of counts) {
    console.log(`   ${c.category}: ${c._count}`);
  }
}

seedModules()
  .catch((e) => {
    console.error('❌ Seed-Fehler:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
